name: library_service
description: Library Service SDK
version: 0.1.0


environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  smithy: ^0.3.0
  smithy_aws: ^0.3.0
  aws_common: ^0.3.0
  built_value: ">=8.4.0 <8.5.0"
  meta: ^1.7.0
  shelf_router: ^1.1.0
  shelf: ^1.4.0




dev_dependencies:

  build_runner: ^2.0.0
  build_web_compilers: ^3.2.0
  build_test: ^2.1.5
  built_value_generator: 8.4.2
  lints: ^2.0.0
  test: ^1.16.0
